apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongo-db
  labels:
    class: db
spec:
  serviceName: mongo-db-svc
  replicas: 2
  selector:
    matchLabels:
      class: db
  template:
    metadata:
      labels:
        class: db
    spec:
      containers:
      - name: mongo-db-container
        image: mongo:6
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          valueFrom:
            secretKeyRef:
              name: mongo-db-secret
              key: DB_USERNAME
        - name: MONGO_INITDB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mongo-db-secret
              key: DB_PASSWORD
        imagePullPolicy: Always
        ports:
        - containerPort: 27017
        volumeMounts:
        - name: mongo-volume
          mountPath: /data/db
  
  volumeClaimTemplates:
  - metadata:
      name: mongo-volume
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 500Mi
      storageClassName: mongodb-sc
 