apiVersion: v1
kind: Service
metadata:
  name: backend-svc
  labels:
    class: backend
spec:
  selector:
    class: backend
  type: NodePort
  ports:
  - name: backend-port
    port: 3500
    targetPort: 3500
    nodePort: 30050
